/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSpecShapeRouteImport } from './routes/api/spec-shape'
import { Route as ApiRelayRouteImport } from './routes/api/relay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecShapeRoute = ApiSpecShapeRouteImport.update({
  id: '/api/spec-shape',
  path: '/api/spec-shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelayRoute = ApiRelayRouteImport.update({
  id: '/api/relay',
  path: '/api/relay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/relay': typeof ApiRelayRoute
  '/api/spec-shape': typeof ApiSpecShapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/relay': typeof ApiRelayRoute
  '/api/spec-shape': typeof ApiSpecShapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/relay': typeof ApiRelayRoute
  '/api/spec-shape': typeof ApiSpecShapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/relay' | '/api/spec-shape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/relay' | '/api/spec-shape'
  id: '__root__' | '/' | '/api/relay' | '/api/spec-shape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRelayRoute: typeof ApiRelayRoute
  ApiSpecShapeRoute: typeof ApiSpecShapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spec-shape': {
      id: '/api/spec-shape'
      path: '/api/spec-shape'
      fullPath: '/api/spec-shape'
      preLoaderRoute: typeof ApiSpecShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relay': {
      id: '/api/relay'
      path: '/api/relay'
      fullPath: '/api/relay'
      preLoaderRoute: typeof ApiRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRelayRoute: ApiRelayRoute,
  ApiSpecShapeRoute: ApiSpecShapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
